### PR TITLE
Support for spaces as indenter, not just tabs

### PR DESCRIPTION
**Pull request by Flurrywinde**

### CODE REVIEW

**Comment by mmitch** [comment]
Sorry for the late reply.
I have not used choicescript-graphviz for the last 5 years.
Do you have a demo file using tabs that I can use to try this out?

I'd like to add some tests and/or replace the indentation detection by a regular expression, but this looks like a nice addition. Thank you!

**Comment by Flurrywinde** [comment]
Here's both a tab-indented and space-indented version of a simple test scene I've been using: [simplevars-spaces.txt](https://github.com/mmitch/choicescript-graphviz/files/8516309/simplevars-spaces.txt)
[simplevars.txt](https://github.com/mmitch/choicescript-graphviz/files/8516310/simplevars.txt)

Recently, I discovered choicescript supports different amounts of spaces, though, so I want to support that too. Here's an example:
```
*label universe1
*choice
  #A relatively normal name
      *choice
          #Aiden
            *set handle "aiden"
          #Andy
            *set handle "andy"

[A/N: All of your actions and inactions will have consequences. You can check the "Show Stats" page to see the reverberations of your actions upon the cosmos.]

[A/N: Would you like to be notified of the consequences?]

*choice
    #[Yes, turn on notifications.]
        [A/N: okay. You might see messages that look kind of like this:]

        Autumn @canonautumnc [b]liked[/b] this!

        [You can always change this in the Stats page.]
    #[No, leave them off.]
        [A/N: okay.]
```
The first *choice initially used two spaces as the indent, but then four spaces, then back to two in the nested *choice. Then, the next *choice uses four spaces. I've been planning to look at the choicescript interpreter's code to see exactly what is and isn't illegal.

In case you're interested, check out my thread [here](https://forum.choiceofgames.com/t/tool-a-stat-analysis-tree/116142) . I made a tool that uses choicescript-graphviz to create the .dot file that then can be further analyzed. Any chance you can guide me on how to add support for *else and *elseif? I've been trying to figure out your code, but I'm not sure what the stack is or how it works to parse the changing indent levels. (I want to add support for *achievement and *scene_list too.)

Regardless, thanks for making choicescript-graphviz. I would never have been able to make my stat analyzer without it!

**Comment by mmitch** [comment]
I can't seem to find an "official" protocol or file format description of Choicescript, so I don't know what is officially legal or illegal.

Here https://www.choiceofgames.com/make-your-own-games/choicescript-intro/ in the "Indentation" section it explicitely states that mixing different amounts of spaces is illegal, so you would not have to support that. But if real scripts in the wild do it that way, you'd have to do it anyway…

**Comment by mmitch** [comment]
You could handle arbitrary combinations of tabs and spaces as indentation by keeping a stack of the previous indentation and then checking indentation of the current line against the current stack indentation:
* equals indentation from stack -> indentation not changed
* equals previous indentation from stack -> pop stack, reduce indentation level
* otherwise -> push current indentation to stack, increase indentation level

But if we can do without that, the code would stay simpler.

**Pull request merged**
